<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/FinDocAI/blob/main/01_fatura_dataset_inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
from PIL import Image
import os
import json
from torch.utils.data import Dataset

In [15]:
!wget -c "https://zenodo.org/records/10371464/files/FATURA2.zip?download=1" -O /content/FATURA2.zip

--2026-10-08 17:25:54--  https://zenodo.org/records/10371464/files/FATURA2.zip?download=1
Resolving zenodo.org (zenodo.org)... 137.138.52.235, 137.138.153.219, 188.185.48.75, ...
Connecting to zenodo.org (zenodo.org)|137.138.52.235|:443... connected.
HTTP request sent, awaiting response... 416 REQUESTED_RANGE_NOT_SATISFIABLE

    The file is already fully retrieved; nothing to do.

In [16]:
!unzip -q /content/FATURA2.zip -d /content/FATURA

replace /content/FATURA/invoices_dataset_final/colored_images/Template3_Instance12.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [17]:
print(os.listdir("/content/FATURA"))

['invoices_dataset_final']

In [18]:
base_path = "/content/FATURA/invoices_dataset_final"
print(os.listdir(base_path))

['strat1_dev.csv', 'strat1_test.csv', 'colored_images', 'Strat2_Split.txt', 'strat1_train.csv', 'Annotations', 'images']

In [19]:
train  = pd.read_csv(f'{base_path}/strat1_train.csv')
val = pd.read_csv(f'{base_path}/strat1_dev.csv')
test = pd.read_csv(f"{base_path}/strat1_test.csv")

In [20]:
print("Shape of Train Data:",train.shape)
print("Shape of Val Data:",val.shape)
print("Shape of Test Data:",test.shape)
print()
print()
train.head()

Shape of Train Data: (7500, 2)
Shape of Val Data: (1250, 2)
Shape of Test Data: (1250, 2)

                  img_path                annot_path
0  Template1_Instance0.jpg  Template1_Instance0.json
1  Template1_Instance1.jpg  Template1_Instance1.json
2  Template1_Instance2.jpg  Template1_Instance2.json
3  Template1_Instance3.jpg  Template1_Instance3.json
4  Template1_Instance4.jpg  Template1_Instance4.json

In [21]:
os.listdir('/content/FATURA/invoices_dataset_final/Annotations')

['Original_Format',
 'COCO_compatible_format',
 'layoutlm_HF_format',
 '.virtual_documents']

In [22]:
train.head()

                  img_path                annot_path
0  Template1_Instance0.jpg  Template1_Instance0.json
1  Template1_Instance1.jpg  Template1_Instance1.json
2  Template1_Instance2.jpg  Template1_Instance2.json
3  Template1_Instance3.jpg  Template1_Instance3.json
4  Template1_Instance4.jpg  Template1_Instance4.json

In [23]:
def template_ids(data):
    for temp_data in data.columns:
        values = data[temp_data].astype(str)
        template = values.str.extract(r"Template(\d+)")[0]

        print(temp_data)
        print(template.dropna().head())
template_ids(train)

img_path
0    1
1    1
2    1
3    1
4    1
Name: 0, dtype: object
annot_path
0    1
1    1
2    1
3    1
4    1
Name: 0, dtype: object

In [24]:
img = Image.open(
    f'{base_path}/images/Template1_Instance0.jpg'
)
print(img.size)
print(img.mode)

(595, 841)
RGB

In [30]:
class FATURADataset(Dataset):
    def __init__(self, dataframe, base_path):
        self.dataframe = dataframe
        self.base_path = base_path

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        sample = self.dataframe.iloc[index]

        return sample


# Making Dataset as object

train_dataset = FATURADataset(train, base_path)
val_dataset = FATURADataset(val, base_path)
test_dataset = FATURADataset(test, base_path)

# Check lengths
print("Train:", len(train_dataset))
print("Validation:", len(val_dataset))
print("Test:", len(test_dataset))

# Get one sample
sample = train_dataset[1]

print("\nSample:")
print(sample)

Train: 7500
Validation: 1250
Test: 1250

Sample:
img_path       Template1_Instance1.jpg
annot_path    Template1_Instance1.json
Name: 1, dtype: object

img_path       Template1_Instance1.jpg
annot_path    Template1_Instance1.json
Name: 1, dtype: object